### PR TITLE
ci: Replace Travis CI with GitHub workflow

### PR DESCRIPTION
**Pull request by thrimbor**
I noticed that Travis CI wasn't properly generating releases for us anymore, and figured the easiest thing would be to move to a GH workflow, like we've done for other repositories.

The workflow currently installs `gcc-multilib` because `imagebld` is built in 32 bit mode. This step can be removed when `imagebld` is built for 64 bit mode and tested to make sure it doesn't cause bugs to appear.
It also doesn't run make with multiple threads because that caused broken builds when I tried it.

/edit:
My fork at https://github.com/thrimbor/cromwell shows that it creates proper releases

### CODE REVIEW

**Comment by MasonT8198** [comment]
I think it'd be of use to have it upload artifacts as well on pull requests for testing purposes

**Comment by thrimbor** [comment]
> I think it'd be of use to have it upload artifacts as well on pull requests for testing purposes

Not a bad idea, added.

**Comment by MasonT8198** [comment]
looks good to me!

**Review by binarymaster — APPROVED** [review]
LGTM, ship it :)

**Comment by Ryzee119** [comment]
Thanks for updating this!

**Pull request merged**
